project:
  type: website
  output-dir: docs

website:
  title: "PQN"
  description: "PQN Personal Blog"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/nampham1106/
      - icon: github
        href: https://github.com/nampq11
      - icon: twitter-x
        href: https://x.com
format:
  html:
    theme: 
      - united
    css: styles.css
    mainfont: "InterVariable, Inter, sans-serif"
    highlight-style: github
    fontsize: 16px
    linestretch: 1.7
    linkcolor: "#2c90e8"
    monofont: "Roboto Mono"
    grid: 
      body-width: 550px
    header-includes:
      <!-- Inter -->
      <link rel="preconnect" href="https://rsms.me/">
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
      <!-- Roboto Mono -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fronts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
 


